2024-06-07 16:32:09,860 - __main__ - ERROR - Attempt 1 failed: HTTPConnectionPool(host='none', port=80): Max retries exceeded with url: /connect (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x101c2d960>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). Retrying in 1 seconds...
2024-06-07 16:32:10,871 - __main__ - ERROR - Attempt 2 failed: HTTPConnectionPool(host='none', port=80): Max retries exceeded with url: /connect (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x101c2ea40>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). Retrying in 2 seconds...
2024-06-07 16:32:12,883 - __main__ - ERROR - Attempt 3 failed: HTTPConnectionPool(host='none', port=80): Max retries exceeded with url: /connect (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x101c2e650>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). Retrying in 4 seconds...
